main:
  project_name: "Conocimiento Personal"
  author: "Lauro Reyes"
  description: "Proyecto para la materia Temas Selectos de Analisis de Datos"
app:
  title: "Conocimiento Personal"
  description: "Proyecto para la materia Temas Selectos de Analisis de Datos"
  version: "0.1.0"
  host: "localhost"
  port: 4000
  debug: true
credentials:
  openai_api_key:
  pinecone_api_key:
  pinecone_index:
  LANGSMITH_TRACING: "true"
  LANGSMITH_ENDPOINT: "https://api.smith.langchain.com"
  LANGSMITH_API_KEY:
  LANGSMITH_PROJECT:
model:
  embedding_model_name: "all-MiniLM-L6-v2"
  model: "gpt-4.1-mini-2025-04-14"
  temperature: 0.4
  